name: chatgpt-code-reviewer
run-name: chatgpt-code-reviewer
on: [pull_request]
jobs:
 chatgpt-code-reviewer:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       repository: magnificode-ltd/chatgpt-code-reviewer
       ref: feature/check-for-limitation-of-openai
       
    - name: start script
      run: node ./dist/index.js
  env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}